
var buttonColours = ["red", "blue", "green", "yellow"]; // only 4 option
var userClickedPattern = [];
var gamePattern = [];

var started = false;// false required to start game 1st time
var level = 0;// initially level is 0

$(document).keydown(function () {// this will work if user presses any key from keyboard
    if (!started) {
        $("#level-title").text("Level " + level);// changing the text of h1
        nextSequence(); // calling the function
        started = true; // true so that again it won't come in this if statement
    }
});

$(".btn").click(function () {// jquery to check if btn is presses if yes then
    var userChosenColour = $(this).attr("id"); // we will store the id of that button in variable 4ids available 
    //for btn i.e.green, red, yellow, blue
    userClickedPattern.push(userChosenColour);// created empty array in so pushing in that array user presses color
    playSound(userChosenColour); // 
    animatePress(userChosenColour);
    checkAnswer(userClickedPattern.length - 1);// array start from 0 that's why length-1
});


function nextSequence() {
    
    userClickedPattern = [];// every time this fn is called we will make userSelected pattern array empty
  level++;// initially its 0 when called
  $("#level-title").text("Level " + level); // updating the level numbers
  var randomNumber = Math.floor(Math.random() * 4);// generating random num between 0 - 3 bcoz we have array of length 4
  var randomChosenColour = buttonColours[randomNumber];// we will select random color from size array 
  gamePattern.push(randomChosenColour); // appending colour generated by random num to game pattern array

  
  $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);// animating this so that user can see whats the color generated
    playSound(randomChosenColour);// playing sound for the colour
  
}



function checkAnswer(currentLevel) {

    if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {// check for every patter suppose at index 0 gamePattern is red 
        // and at index 1 its blue user 1st select blue so userClickedPattern array has only 1 element 
        // so it will chck gamePattern[0] === userClickedPattern[0] this is false so game is Over
        
        // console.log("success");
        if (userClickedPattern.length === gamePattern.length) {// posibilty that user choose color at last element is same as gamePattern
            // last element so no checking if both length are same or not
            setTimeout(function () {
                nextSequence();// if true after 1sec call the next sequence again
            }, 1000);
        }
    } else {
        // console.log("Failed");
        playSound("wrong");// else will run if above if is false
        $("body").addClass("game-over"); // adding new class to body
        $("#level-title").text("Game Over, Press Any Key to Restart");// changing the text of h1
        setTimeout(function () {
            $("body").removeClass("game-over");// removing game-over class after 0.2 sec so its like a red flash
        }, 200);
        startOver();
    }
}


function animatePress(currentColor) {
    $("#" + currentColor).addClass("pressed");
    setTimeout(function () {
        $("#" + currentColor).removeClass("pressed");
    }, 100); // 0.1sec
    
}

function playSound(name) {
    var audio = new Audio("sounds/" + name + ".mp3");// object of Audio
  audio.play();// calling the method of Audio object    
}

function startOver() {
    // this will reset the game
    level = 0;
    gamePattern = [];
    started = false;
}